import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const lexend = Lexend_Deca({
  variable: "--font-lexend",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Groovio",
  icons: "/logo.png",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexend.variable}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
